#!/usr/bin/env python
import base64
import argparse
parser = argparse.ArgumentParser(description="Simple File Encryptor Script")
f_group = parser.add_mutually_exclusive_group(required=True)
f_group.add_argument("-f", "--file", action="store_true", help="Filename")
f_group.add_argument("-s", "--string", action="store_true", help="String")
s_group = parser.add_mutually_exclusive_group(required=True)
s_group.add_argument("-e", "--encode", action="store_true", help="Whether to encode the file")
s_group.add_argument("-d", "--decode", action="store_true", help="Whether to decode the file")
args = parser.parse_args()


def encode(file):
    with open(file, "rb") as File:
        str = base64.b64encode(File.read())
    pf = open(file + ".new", "wb")
    pf.write(str)
    pf.close()


def decode(file):
    with open(file, "rb") as File:
        str = base64.b64decode(File.read())
    pf = open(file + ".new", "wb")
    pf.write(str)
    pf.close()


def s_encode(string):
    print(base64.b64encode(string))


def s_decode(string):
    print(base64.b64decode(string))


encode_ = args.encode
decode_ = args.decode
if args.file:
    file = input("file path: ")
    if encode_ and decode_:
        raise TypeError("Please specify whether you want to encode or decode.")
    elif encode_:
        encode(file)
    elif decode_:
        decode(file)

if args.string:
    string = input('input string: ')
    if encode_ and decode_:
        raise TypeError("Please specify whether you want to encode or decode.")
    elif encode_:
        s_encode(string)
    elif decode_:
        s_decode(string)
