#!/usr/bin/python3
import argparse
from cryptography.fernet import Fernet
parser = argparse.ArgumentParser(description="Simple File Encryptor Script")
parser.add_argument("file", help="File to encrypt/decrypt")
parser.add_argument("-g", "--generate-key", dest="generate_key", action="store_true",
                    help="Whether to generate a new key or use existing")
parser.add_argument("-e", "--encrypt", action="store_true",
                    help="Whether to encrypt the file, only -e or -d can be specified.")
parser.add_argument("-d", "--decrypt", action="store_true",
                    help="Whether to decrypt the file, only -e or -d can be specified.")
args = parser.parse_args()


def write_key(file):  # Generates a key and save it into a file
    key = Fernet.generate_key()
    with open(file + ".key", "wb") as key_file:
        key_file.write(key)


def load_key(file):  # Loads the key from the current directory named `key.key`
    return open(file + ".key", "rb").read()


def encrypt(filename, key):  # Given a filename (str) and key (bytes), it encrypts the file and write it
    f = Fernet(key)
    with open(filename, "rb") as file:  # read all file data
        file_data = file.read()  # encrypt data
    encrypted_data = f.encrypt(file_data)
    with open(filename, "wb") as file:  # write the encrypted file
        file.write(encrypted_data)


def decrypt(filename, key):  # Given a filename (str) and key (bytes), it decrypts the file and write it
    f = Fernet(key)
    with open(filename, "rb") as file:
        encrypted_data = file.read()  # read the encrypted data
    decrypted_data = f.decrypt(encrypted_data)  # decrypt data
    with open(filename, "wb") as file:  # write the original file
        file.write(decrypted_data)


file = args.file
generate_key = args.generate_key
if generate_key:
    write_key(file)
key = load_key(file)
encrypt_ = args.encrypt
decrypt_ = args.decrypt

if encrypt_ and decrypt_:
    raise TypeError("Please specify whether you want to encrypt the file or decrypt it.")
elif encrypt_:
    encrypt(file, key)
elif decrypt_:
    decrypt(file, key)
else:
    raise TypeError("Please specify whether you want to encrypt the file or decrypt it.")
